/* eslint-disable @typescript-eslint/no-var-requires */
/* eslint-disable @typescript-eslint/ban-ts-comment */
/* tslint:disable */
// @ts-nocheck
const { writeFile, existsSync, mkdirSync } = require('fs');
require('dotenv').config();

function writeFileUsingFS(targetPath, environmentFileContent) {
  writeFile(targetPath, environmentFileContent, function (err) {
    if (err) {
      console.log(err);
    }
    if (environmentFileContent !== '') {
      console.log(`wrote variables to ${targetPath}`);
    }
  });
}

// Providing path to the `environments` directory
const envDirectory = './src/environments';

// creates the `environments` directory if it does not exist
if (!existsSync(envDirectory)) {
  mkdirSync(envDirectory);
}
// choose the correct targetPath based on the environment chosen
const targetPath = './src/environments/environment';
// creates the `environment.*.ts` and `environment.ts` file if it does not exist
const target = `${targetPath}.ts`;
writeFileUsingFS(target, '');
//actual content to be compiled dynamically and pasted into respective environment files
const environmentFileContent = `
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    BASE_URL: '${process.env.BASE_URL}'
  };
`;
// appending data into the target file
writeFileUsingFS(target, environmentFileContent);
/* tslint:enable */
